/**
 * Build the client half: esbuild bundles src/client/index.tsx to CJS, then we
 * wrap it in dsh's lazy module factory (`window.__ModuleLoader__.load`). Peer
 * modules (react, dsh client runtime) stay external and are resolved by the
 * shell's module table at materialization time.
 */
import { build } from 'esbuild'
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const out = join(root, 'lib', 'client.js')

const result = await build({
  entryPoints: [join(root, 'src/client/index.tsx')],
  bundle: true,
  format: 'cjs',
  jsx: 'automatic',
  target: 'es2022',
  platform: 'browser',
  external: ['react', 'react-dom', 'react-dom/*', 'react/jsx-runtime', '@deepseek-ai/*'],
  write: false,
  minify: false,
})

const wrapped = `"use strict";
// dsh-branchspace client bundle — generated by scripts/build-client.mjs
window.__ModuleLoader__.load({
  id: "dsh-branchspace",
  factory: function (require) {
    var module = { exports: {} };
    var exports = module.exports;
${result.outputFiles[0].text}
    return module.exports;
  }
});
`

await mkdir(dirname(out), { recursive: true })
await writeFile(out, wrapped)
console.log(`client bundle written: ${out} (${wrapped.length} bytes)`)
